slam_toolbox:
  ros__parameters:

    # Plugin and mode
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: None

    # Topics / frames — match your robot
    odom_frame:  odom
    map_frame:   map
    base_frame:  turtlebot/base_link   # matches your robot_base_frame
    scan_topic:  /scan
    use_sim_time: false

    # Map update behavior
    resolution: 0.05
    max_laser_range: 5.0
    minimum_travel_distance: 0.1
    minimum_travel_heading: 0.1
    map_update_interval: 5.0

    # Performance
    transform_publish_period: 0.02
    transform_timeout: 0.2
    tf_buffer_duration: 30.0
    stack_size_to_use: 40000000

    # Don't start a brand new map
    mode: localization
    map_file_name: /home/katallen/sandbox/src/block-painting-helper/maps/kat_lab_map
    map_start_at_dock: false